force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Picklist</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CasePriorityService.cls
public class CasePriorityService {

    public static void applyPriority(List<Case> caseList) {

        for(Case c : caseList){

            if(c.VIP_Customer__c == true ||
               c.Product__c == 'Payment' ||
               (c.Subject != null && c.Subject.containsIgnoreCase('Urgent')))
            {
                c.Priority = 'High';
            }
            else{
                c.Priority = 'Medium';
            }
        }
    }
}